### ISSUE TITLE
Find related services near arbitrary location

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1048]
Open the app on some topic, click find relates services, observe that the list of results is sorted by distance from the device location. Desired is to be able to enter the name of a location such as "Surrey" in order to get results sorted by the distance to the named location, as consistent as possible with the results from the Algolia search.

### Acceptance Criteria 
- [ ]  There is a field on the service listing page that allows the user to enter a location
- [ ] If the location is specified, the app hits geocoder to get the lat/long for the location
- [ ] If the field is empty, the device location is used [to be confirmed, see mocks when they're ready]
- [ ] The location from geocoder or from the device is submitted in the request to the server

Note that we are in the process of doing a fair amount of refactoring around the search. This will affect the code for calling the geocoder endpoint. The plan is to merge your PR first. So use existing code to access geocoder, but don't refactor it or make a lot of changes outside the component.

**Comment by bensinjin** [comment]
Moving @cherrielam 's ticket for this here:

We would like to add the location search function to the topic-services page. This is because: As a user, I would like to adjust the service results on a topic in order to search in the location that is of interest to me. This is particularly important for users who want to use AA pre-arrival.

Mock is [here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5e6ab3e4e90d37189ac6645e)

### Acceptance Criteria 
- [ ]  Topic>Services List has location search function as reflected in mocks, and service list updates according to the input location.

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
QA: Open the service search for a topic, observe many services are listed, focus on search input field, enter "Kelowna", hit Search, observe fewer services are listed, focus on search input field, clear the field by hitting X, hit search, expected is that many services are listed, observe that the listing still shows results for Kelowna.

**Comment by bensinjin** [comment]
Thanks, the fix has been pushed. I've noticed another potential issue. Because this component only triggers the loading screen when we actually start searching for services there is a delay in displaying it while the location is being fetched. There are two potential fixes:

A) Easy approach: leave the search expanded, which displays the buttons as inactive while the location lookup completes, collapse it after to indicate we've found the location

B) Longer/Refactor approach: Move the `isFetchingLatLng` state up into the parent component so we can display the loading screen when child component performs the lookup

Let me know your thoughts, thx!

**Comment by cherrielam** [comment]
@bensinjin I see what you mean now, I agree that this is an issue because it gives the user the impression for a split second that the search has run/not run/nothing happened

My preference is B... we should give the users the sense that something is happening (loading) sooner, rather than A which might give the user the feeling that the search has frozen or something while the lookup is happening? But either sounds like an improvement from currently. @rasmus-storjohann-PG may be a better judge of which one is better worth the time vs impact

**Comment by bensinjin** [comment]
Thx @cherrielam! We've decided to leave this for now and circle back if it becomes an issue later as more pressing work needs to be addressed.

**Comment by jparlina** [comment]
Tested on Staging V1.25.0, server V1.3.24 on iOS 7s in Burnaby:
- Selected topic "Applying for a driver's licence" > clicked "Find related services near me" > services in Burnaby showed up at the top > entered "Surrey" in the location field > services in Surrey then appeared on the  top of the list.  
- Selected topic "Register for English classes " > clicked "Find related services near me" > services in Burnaby show up on top of the list" > entered "Victoria" in the location field > only services in Victoria showed up. 

Acceptance Criteria:
- [X] Topic>Services List has location search function as reflected in mocks, and service list updates according to the input location.
