### ISSUE TITLE
Fonts in Dialog about services only in English are not consistent

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1070]
The fonts that are in the Dialog that says "Services are only in English..." are not consistent. Here are the issues:

- iOS: I don't think the link ("Call BC211") and the rest of the body text are the same size, see image:
![Screen Shot 2020-03-20 at 10.22.48 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/8080d2de-a41e-4533-a530-79afb8ae9d1c)

- Android: Links are in the system font, body text is in Avenir. They should all be in Avenir
![Screenshot_20200312-105521_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/f50ca862-a931-4632-8b26-5a1c086fd664)

### Acceptance Criteria 
- [x]  on iOS and Android, font size in the dialog is consistent between "Call BC211" and the rest of the text
- [x] on Android, text and links are all in Avenir

### Steps for QA: 
1.

**Comment by bensinjin** [comment]
Regarding your first point, the size of the text is the same, it's only the weight of the text that's different. This is what it looks like without the 900 weight (iOS):
<img width="318" alt="Screen Shot 2020-04-30 at 1 17 20 PM" src="https://user-images.githubusercontent.com/3228323/80755037-f113ba80-8ae4-11ea-88cc-75ce6477227a.png">, both the greyish and teal text are set to `fontSize: 15`.

Regarding your second point, you're right, they're not the same fonts, on Android we have to use `fontFamily: AvenirBlack` because we cannot just set the weight to 900 as we do on iOS. This is not the system font but it maybe doesn't look exactly the same as Avenir when side-by-side.

**Comment by tomy-pg** [comment]
@cherrielam  ^

**Comment by cherrielam** [comment]
Checked on iOS and Android, looks good, thanks so much for fixing and explaining! @bensinjin
