### ISSUE TITLE
When location is a known city such as Burnaby, filter services on the address city field

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1141]
So we could try to filter the results in cases where a recognized city, such as "Surrey", is entered as the location, we can only show results with "Surrey" in the city field of the address. For location strings that are not recognized as cities (e.g. street addresses or postal code) we fall back on geocoder. Also for cities, we find that geocoder tends to use poorly chosen lat/longs for the city, we can hard-code our own values. Tricky to make this work in algolia.

Acceptance criteria
- [ ] When searching and giving as location the name of a city, match service providers whose address.city field matches the given city.

Questions:
- [ ] Do we hardcode some cities or all BC municipalities?
- [ ] How do we handle typos in the city name?
- [ ] Can we make this work in Algolia?

**Comment by rasmus-storjohann-PG** [comment]
Jean's comment outlining the problem:
```
Tested on Algolia using index ArrivalAdvisorProductionVersion1:

The search results are good enough for now (better than before). Results for Vancouver are better than other regions maybe due to the content of bc211 data. The taxonomy immigrantsethnocultural-groups helps to focus the bc211 data for newcomers. There are some other issues (e.g. libraries) which I think are more related to how bc211 target users are different from AA users. See more detailed testing results on this spreadsheet.

For future consideration: push more relevant results (matching words, taxonomy terms, and for_newcomers) to the top within a certain radius. Based on our testing with newcomers, users are willing to look at further locations if they are more relevant services.

Is it possible to match the "city" that users entered in Location with "city" in bc211 service records? As an example, for average users, it's confusing to see services in New Westminster or Delta at the top of the search results when searching for Surrey, and services in Surrey appear lower on the list.
```

**Comment by rasmus-storjohann-PG** [comment]
@tudatn comment on closely related issue:
I notice that the geolocation (latlong) from geocoder.ca API is not at the center of the city but closer to the city boundary. Here what we got if we search for Surrey:
Screen Shot 2020-03-26 at 11 15 06 AM
The return location is very close to the boundary with New Westminster. Cause we are passing 'aroundLatLng' to Algolia with precision of 5000m, it's highly likely the top records may be in New Westminster. A similar problem can happen to other cities.
Currently I don't see any parameter that we can pass to geocoder.ca API to enforce it to return the center coordinate of the city. We may want to consider using different services or even manually create a dictionary <City, Latlng> to solve this problem.

**Comment by ian-lin-PG** [comment]
Having interpreted the comments thus far. One actionable item we could pursue is to show only results that matches a certain location. On the front of filtering by cities, there's 2 possibilities:
1) Filter the algolia results in app. This means the results will most certainly be under 20 items that algolia returns. This does not account for typos and could be slower due to extra processing.

2) Include addresses as part of the searchable attribute and include city as part of the search term. Algolia have built in typo handling and that extends to the city as well. I have created `dev_match_city` index for testing purposes. Do carry out normal search terms, but also add the city after the usual search term.

As for potentially hardcoding latlongs to city, we have a csv with the geocoder latlong given a city. We can update that csv either manually or use a better location api. @rasmus-storjohann-PG  @jparlina I am free to discuss either points with you when you have time.

**Comment by rasmus-storjohann-PG** [comment]
Include location in search terms sent to Algolia, if and only if we believe the location is a city name. Heuristic for identifying a location string as a city name (and not a street address or postal code) is that the location string contains no digits.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG @jparlina is the current work around sufficient to close this issue?

**Comment by jparlina** [comment]
I think it's good enough for now; it's better than before when using lat long. We'll need to test with actual users and get their feedback once we get the rolling user testing/research going.

**Comment by rasmus-storjohann-PG** [comment]
Done
