### ISSUE TITLE
Display "My Location" in location search bar on Topic-Services page if the user's mobile Location Services are enabled

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1195]
When a user opens the Topic-Services page for the first time, they get an alert to _Allow Location Services_ on this app. After the Location Services is allowed, the Topic-Services page displays services based on their location. But the location search bar is empty, they are presented the option to add "My location". This gives the user a wrong impression because now they are unsure whether it is searching from their location, and if it is, why do they need to select "My Location" again?

Recommendation: Once the user opts into Location Services, the location search bar should show "My Location" within the bar. See below:

![Screen Shot 2020-06-11 at 1.16.27 PM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/8443745c-bd8d-4fbb-b19a-a77782869b0e)

![Screen Shot 2020-06-11 at 1.16.38 PM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/cd86764b-f39e-4544-abb1-540b81fd0894)

### Acceptance Criteria 
- [ ]  Once Location Services is enabled, the location search bar should be filled with "My Location" (and the option to exit with the x). 
- [ ] The Location search bar should be empty if the user chooses not to enable Location Services
- [ ] Apply the same logic to Search as applicable

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
@tomy-pg can you review this issue too see if it accurately reflects what you observed? @jparlina can you add any discrepancies you noticed and what you think you observed here?

**Comment by jparlina** [comment]
@cherrielam I like your suggestion to fill in the location search bar with "My Location" when the user enables Arrival Advisor to access their location. The question then, can we add a copy to let users know that they can replace "My location" by clicking the x and enter city, address, or postal code if they wish to search other locations? Otherwise, how would they know that they can search by location under Topic-Services page?

While looking into this, noticed other bugs:

1. When I selected "Don't Allow" here, we still have this old error message which doesn't let users know that without enabling their phone location, they can still search by entering city, address, or postal code. 
![Screen Shot 2020-06-15 at 6 10 26 PM](https://user-images.githubusercontent.com/48343061/84720753-c5814e00-af33-11ea-8011-58d34a9249fd.png)

2. We should also remove the "My location" button from the Topic-Services page once the user selects "Don't Allow" or "Allow once" when asked for their geo location. Otherwise, when the click "My location" they'll get the _Invalid Location_ error message instead of the Enable Location Services" error message. 
![Screen Shot 2020-06-15 at 6 53 06 PM](https://user-images.githubusercontent.com/48343061/84723016-82c27480-af39-11ea-8958-8477f362dd7f.png)

**Comment by ian-lin-PG** [comment]
@tomy-pg Currently the my location is filled in even before accepting location permissions. If I reject the field is still filled in as well.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-10 at 13 04 15](https://user-images.githubusercontent.com/52009863/107572015-8974ba80-6ba0-11eb-81fb-b08694372161.png)

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
