### ISSUE TITLE
Wrong phone number dialed for numbers with local extension

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1232]
Search for "Aunt Leah" in services, look up service "Support Link", see phone numbers with suffix "Local 212", click to call the number. Expected is to see the phone about to call the correct number. Observed is phone is about to call a number with "local 212" transcribed to digits.

### Acceptance Criteria 
- [x]  The correct number will be called

**Comment by ian-lin-PG** [comment]
QA Passed, calls correct phone number instead of the extension.
![Screenshot_20200817-101809](https://user-images.githubusercontent.com/52009863/90424613-3dbed980-e073-11ea-852f-0119b3f717c3.jpg)
![Screenshot_20200817-101817](https://user-images.githubusercontent.com/52009863/90424620-3ef00680-e073-11ea-8f7d-bebcbc63147e.jpg)
