### ISSUE TITLE
Update Sentry SDK

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1268]
From a recent sentry crash report: "We recommend you update your SDK from version 1.4.2 to version 1.7.2."

Link to the [page](https://docs.sentry.io/platforms/react-native/?_ga=2.203861271.688804585.1599063718-1960448892.1579901980) about upgrading.

### Acceptance Criteria 
- [ ]  We run with the current version of the Sentry SDK

**Comment by tomy-pg** [comment]
Since we are using expo, we use the expo's sentry SDK, as opposed to react native's sentry SDK in the link provided in the main story. Here is the [link to the page](https://docs.expo.io/versions/latest/guides/using-sentry/) with more details.

I ran `yarn outdated` and found that sentry-expo is not an outdated package in our project.

**Comment by ian-lin-PG** [comment]
I agree with @tomy-pg , we use the `sentry-expo` library instead of expo. I will close this issue.
