### ISSUE TITLE
Navigation history (back button) bug

### ISSUE THREAD

**Issue by tnightingale** [pg-irc/pathways-frontend#130]
@bensinjin and I got a little closer to figuring out what's going on with navigation history (broken back button) yesterday afternoon. I have included a diagram below to explain (yay ASCII diagrams!!):

```
Pages:
H = Default/initial route (currently same as Questionnaire but has it's own route)
Q = Questionnaire
P = My plan
L = Learn

Navigation |   | History stack
--------------------------
Start      | H |
> P        | H | P
> L        | H | P L
> Q        | H | P L Q
... At this point we can navigate back three times and will follow the sequence:
... Q, L, P, H
... Resuming from above state, if we navigate to L, we would expect the
... following history stack:
> L        | H | P L Q L
... We expect to be able to navigate back four times following the sequence:
... L, Q, L, P, H
... Instead we discover that we can only go back twice: L, P, H; the stack
... actually resembles this:
           | H | P L

I suspect it has something todo with the stack getting truncated when you visit a page
that already existed in the stack. This is reproducible with any permutation of
navigations. 
```
Related issues: #102 #74 #76 #64 #34 #53 

_There is also a similar but different problem happening with Task Detail pages, Ben think's it's due to the task id route parameter not being tracked in the history stack state._

**Comment by tnightingale** [comment]
@trisapeace you might be interested in this.

**Comment by trisapeace** [comment]
Thanks! Yes, that's exactly what I was experiencing. Good description (and beautiful ASCII art). What was strange is that I could see in the debugger that it was keeping the whole stack correctly when navigating forward through the pages. So it wasn't doing the weird truncation until you start pushing Back. To me it feels like they are searching the stack from the bottom to find the first matching instance instead of popping off the top. 

That's frustrating that it's happening with the tasks too. From what I was seeing, it was keeping the whole route as a string, which would include the task ID, but I could be wrong because my investigations were before Ben added his stuff.

**Comment by rasmus-storjohann-PG** [comment]
Closing, this functionality has been completed under a different story
