### ISSUE TITLE
Expo splash screen appears where our own should be

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1318]
Booting up the app, we now see an ugly low res Expo splash screen. This is a regression very likely caused by a recent expo library upgrade.

### Acceptance Criteria 
- [x]  At boot up, our own splash screen appears.

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
@cherrielam please give a link to the splash screen we should use (just an image, no buttons, language selectors, etc)

**Comment by tomy-pg** [comment]
This has regressed again in staging release 1.58.0

**Comment by tomy-pg** [comment]
https://forums.expo.io/t/after-expo-upgrade-appear-expo-splash-in-my-app/46048

After some sleuthing, it seems like upgrading `expo-cli` fixes the problem for some people. I upgraded and side-loaded the app and I now see the splash screen and icon fixed. `expo-cli` apparently is not supposed to affect any of this but I along with some others in the expo community have seen this fixed by upgrading. 

@rasmus-storjohann-PG and @ian-lin-PG please run `yarn global add expo-cli` before next release.

**Comment by ian-lin-PG** [comment]
PASS QA 1.62.0
