### ISSUE TITLE
Handle organizations when they are offline

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1323]
@tomy-pg commented on [Wed Dec 16 2020](https://github.com/pg-irc/pathways-backend/issues/581)

Similar to search and topic services the organizations component and service for organizations component need to have error screens for when users are offline and exception.

@cherrielam to provide mock for error screen for when organization data is not available.

### Acceptance Criteria 
An error screen exists for situations when:
- [ ] Users are offline
- [ ] An exception occurs

### Steps for QA: 
1. Navigate to topics page
2. Select any topic
3. Click on the button `Find related services near me`
4. Click on any service on the screen
5. When you are brought to the service's detail page, turn your phone to airplane mode
6. Click on name under the label `Provided by:`
- [ ] notice you see an error screen notifying the user that they are offline
7. Turn airplane mode back off
8. Go back to the same service detail page
9. Click on the name under the label `Provided by:`
- [ ] notice you see the Organization detail page now.

**Comment by ian-lin-PG** [comment]
@cherrielam here are the reference screenshots of organization page. It's worth noting that this page has bigger dimensions compared to topic services page or search page where we had the other error screens. The offline screen is most important followed by a generic error screen. Thanks a lot!

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-16 at 13 28 28](https://user-images.githubusercontent.com/52009863/102408573-a6c34900-3fa2-11eb-8ef3-6fc4bdfd45f4.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-16 at 13 18 17](https://user-images.githubusercontent.com/52009863/102408455-74b1e700-3fa2-11eb-89c5-8aaa4c4de18c.png)

**Comment by cherrielam** [comment]
@tomy-pg @jparlina @ian-lin-PG
@Melanie-PG and I made the following suggestions re: copy on the error state:

https://zpl.io/29X3nRY - For organizations error: Can't reach the internet. Please connect to the internet and try again. **Note: this is same as previous except removed one sentence**

For search error and topic services error: Can't reach the internet. **Search** is not available offline. Please connect to the internet and try again. **Changed "Services are" to "Search is" due to confusion around the "Search" terminology. Also because organizations will maybe! hopefully! in the future! be in Search.

https://zpl.io/V15kWoJ 
https://zpl.io/bJW1A7r

**Comment by tomy-pg** [comment]
@Elvislogan could you please QA this issue?

**Comment by Elvislogan** [comment]
Hi Tomy

Sure I will. Please have I been added to the Staging server yet?

Best regards,
Elvis

**Comment by tomy-pg** [comment]
Hey Elvis, 

I will email you with details for how you can download the staging app!

**Comment by Elvislogan** [comment]
Okay. I am waiting

**Comment by tomy-pg** [comment]
Staging 1.62.0 - PASS
