### ISSUE TITLE
Search function is not defaulting to use my location

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1360]
Search: Don't put location, results are sorted with N/A for address at the top, then Burns Lake, then Terrace, so the results don't make sense.

Problem is observed on both staging and production.

This is a regression.

Search from Burnaby:

![image.png](https://images.zenhubusercontent.com/59ce7d37b0222d5de479a74f/186e4cb3-1e56-4120-b66a-bddc33ad6b5b)

Search from Vancouver:

![image.png](https://images.zenhubusercontent.com/59ce7d37b0222d5de479a74f/f74287af-9794-4fa1-b660-bd8337f3f026)

### Acceptance Criteria 
- [x]  Search results are sorted correctly

**Comment by ian-lin-PG** [comment]
After consulting with @cherrielam and @Melanie-PG, we decided on some next steps:
1. Ask for location permission when open search page first
2.  If user allow for location, update the location input field with `My Location`
3. Search results will reflect using `My Location` and the device location
4. If user does not allow for location, the search location field will be blank
5. Have similar behaviour for topic service list page

Additional brain storming required for the following cases:
1. Design reasonable response for search without location, or have feedback prompting entering location
2. Update the enable location service error screen from topic service listing page

**Comment by tomy-pg** [comment]
We will be using a default value on initial launch.
Location input should show Vancouver.

**Comment by ian-lin-PG** [comment]
After consulting with @cherrielam and @Melanie-PG it's been decided to leave the input field blank and implicitly pass in a hardcoded Vancouver latlong into the algolia query. A separate issue is created for sorting city by a location but not excluding them, see issue #1381.

**Comment by rasmus-storjohann-PG** [comment]
> After consulting with @cherrielam and @Melanie-PG it's been decided to leave the input field blank and implicitly pass in a hardcoded Vancouver latlong into the algolia query. A separate issue is created for sorting city by a location but not excluding them, see issue #1381.

We need to remember to default to Winnipeg in the MB version

**Comment by tomy-pg** [comment]
The original issue outlined by @rasmus-storjohann-PG still appears. Services with n/a address show up at the top.

However, the new acceptance criteria mentioned by @ian-lin-PG passes. I will leave this issue open for now.

**Comment by rasmus-storjohann-PG** [comment]
@ian-lin-PG and @cherrielam to have a discussion and come up with a design for a solution to this problem

**Comment by cherrie-pg** [comment]
Hi! So I noticed that this is still an issue (empty location will show N/A addresses at the top) in Search. 

Tagging @alysha-PG and @rasmus-storjohann-PG for final decisions

## Empty location on search page

My suggested design of the experience is as follows:

1. Ask for location permission when open search page first
2. If user allow for location, update the location input field with `My Location`
3. Search results will reflect using `My Location` and the device location
4. If user does not allow for location:

**OPTION A:**
5. Show Search with location search bar active (the cursor should be in the location search bar and the keyboard is opened)
6. If user tries to proceed without entering a location, prompt user to input location (eg. have native alert that says: "Please enter a location to search") and do not allow search until location is entered

![Search with no location OPTION A](https://user-images.githubusercontent.com/21990736/145319000-2c2af5fd-193c-4327-87ea-8a5f1cd935c0.png)



**OPTION B:**
5. Continue the search by filling a default location based on province. For BC, the default location is Vancouver; for MB, the default location is Winnipeg.
6. Display the defaulted location in the location input, so that the user knows that a location was entered, and they can change it.

** **Note: Option B should only be done if we re-open and address https://github.com/pg-irc/pathways-frontend/issues/1381 - which causes results to SORT by location and not exclude those outside of location. So "Vancouver" should sort the results with Vancouver at the top (but still show results in Surrey below) and "Winnipeg" should sort the results with Winnipeg at the top (but still show Brandon, MB below).**

![Search with no location OPTION B](https://user-images.githubusercontent.com/21990736/145319190-cecfdca5-6ec8-428d-b4f0-8742fbd7a092.png)



## Empty location on topic-services page

I would suggest that we apply similar behaviour for the topic-services (Find related services near me) page.

Right now the page looks like this:
![IMG_0536](https://user-images.githubusercontent.com/21990736/145316781-10e61eb6-d1b4-4686-b84c-567e608b8ea2.PNG)

We should remove or change the "Enable location services" message because Location services is not required to use this page. Instead, we can apply a "Turn on location services" prompt when users click the "My Location" button (right now Clicking "My Location" when Location services is turned off takes them to their native location controls, which I think is fine, we can keep it as is without adding a prompt in the flow).

Then, to mirror the flow above, the experience of opening topic-services is as follows:
1. If user turned on "My Location" or conducted a search where they filled in a location, when user clicks "Find related services" on a topic, open topic-services with location input matching previous input (ie. My Location or location from prior search)
2. If user has not turned on Location Services, ask for location permission when opening topic-services page
3. If user allow for location, update the location input field with `My Location`
4. Topic-service results will reflect using `My Location` and the device location
5. If user does not allow for location:


**OPTION A**
6. Show empty topic-services page with location search bar active (the cursor should be in the location search bar and the keyboard is opened)
7. If user tries to proceed without entering a location, prompt user to input location (eg. have native alert that says: "Please enter a location to search") and do not allow search until location is entered

![Topic-services with no location OPTION A](https://user-images.githubusercontent.com/21990736/145320003-6ba1d554-9f5d-4712-8929-8a78f4eb1517.png)

**OPTION B**
6. Continue the topic-services search by filling the location input with a default location based on province. For BC, the default location is Vancouver; for MB, the default location is Winnipeg.
6. Display the defaulted location in the location input, so that the user knows that a location was entered, and they can change it.

![Topic-services with no location OPTION B](https://user-images.githubusercontent.com/21990736/145320020-948cefaa-1a37-4882-b9f6-db60bb02b572.png)
