### ISSUE TITLE
App crashes when changing between LTR & RTL on any page that is not the homepage

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1388]
On any page except the homepage (tested Topic Services, Search, Bookmarks, Learn...), when I change from English/French/etc (any LTR language) to Arabic, the app crashes. It also crashes when I change back from Arabic to an LTR language. 

On Staging 1.62.0 - iPhone XS

### Acceptance Criteria 
- [x]  App does not crash when changing between LTR/RTL languages regardless of the page the user is on. App behaviour should be same as the current production - switching from LTR to RTL on any page returns the user to the homepage in the newly selected language.

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
I am removing the show stopper label. While crash bugs generally are show stoppers, we have good reason to believe the bug is caused by a third party library, and the crash is rare, since it only happens when changing the language to AR. A user will see the crash once, restart the app and it works fine from that point on. We can monitor this crash in Sentry to get a sense of how often it actually happens

**Comment by tomy-pg** [comment]
Staging version 1.63.0 This is currently not breaking on my iPhone X

**Comment by Melanie-PG** [comment]
It no longer crashes, but it is now glitching before settling on the homepage 

https://user-images.githubusercontent.com/76975404/109368282-7bd05d80-784d-11eb-92f3-84c56f22af33.MP4

**Comment by cherrielam** [comment]
Agree, despite having a bit of lag, this is mostly fixed.

**Comment by cherrielam** [comment]
Closing, @tomy-pg will make a separate issue about the reload delay
