### ISSUE TITLE
Get Travis working again for server and client

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1466]
Travis CI is not working for the server (pathways-backend) or the client (pathways-frontend). Good thing for the new hire to get started with. See also #1467 for more details on this issue.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG since the end of last year https://travis-ci.org/ have been retired for https://travis-ci.com/. We need to migrate our travis integrations that way. I tried doing it on my own, but only the QA repo and the content repo migrated. I think this has something to do with you being the owner of the pg-irc account.

Further instructions on migration can be found [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).
