### ISSUE TITLE
Arabic UX issues in the client

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1598]
If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by Farouk-PG** [comment]
When switching to Arabic and clicking on "About Arrival Advisor", we see "undefined" instead of the names of the websites the links direct to. Also, look at the (<0>) tags we see under each undefined.

![unnamed](https://user-images.githubusercontent.com/89798867/131748121-292c3794-bfbb-4508-af84-a3b80323880d.jpeg)

**Comment by Farouk-PG** [comment]
Reproduce bug: with both Arabic and English, click under "brought to you by" to open creators' info.
Observation:  Two curly brackets {0} 
Expectation: No irrelevant signs
 
![bug](https://user-images.githubusercontent.com/89798867/131750289-be282ee3-f0c2-485b-9b11-159d4580e296.jpeg)
