### ISSUE TITLE
MB211 services still show HTML markdown

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1626]
When I go to Search, I expect to search for services and not see HTML markdown. Instead, I see HTML markdown in service description.

![Image from iOS (10)](https://user-images.githubusercontent.com/85197659/134596285-24cacc8b-0433-4bfb-8a4e-e1c85ce95672.png)

### Acceptance Criteria 
- [ ]  Service description in English does not show HTML markdown

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
Example service to look up: MB > Education > Continuing Education for Adults > Find related services > Near Winnipeg > Adult Learning and Literacy.

**Comment by rasmus-storjohann-PG** [comment]
Some notes on how this was QAed:
Ran the data processing pipeline (mongo) on the file before and after the html cleanup. Since this affects service data, compared the two algolia.json files generated with data before and after the html cleanup. The data needs to be sorted to run diff, did that as follows:
```bash
jq '.components.rows|=sort_by(._id)' algolia.json > algolia.sorted.json
```
then compared the files using diff:
```bash
diff -w algolia.sorted.json ../out-html-not-clean/algolia.sorted.json | less
```
Reviewed the changes to confirm that only HTML tags had been affected.

**Comment by alysha-PG** [comment]
html markdown GONE in both fr and en
