### ISSUE TITLE
Topic sub headings are too small, don't stand out from the body text

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1671]
Expected is that subheadings in topic text is easy to see because of distinct style (larger font side, bold, increased spacing above and below. Observed is that such headings currently look almost exactly the same as the body text.

This can be solved through the use of styles, see `markdownStyles` in `/pathways-frontend/src/application/styles.ts`

### Acceptance Criteria 
- [x]  Headings of level 1, 2 and 3 are all clearly distinct from each other and from body text in the app topics.

### Steps for QA: 
1.

**Comment by cherrielam** [comment]
H1 is too big since it looks bigger/equivalent to the topic title itself, and there is an awkward space at the top if the H1 is at the start of the topic detail 

Not sure if it is possible to style in such a way that if it is the first H1, there is no margin-top... otherwise we may need to find a different way to add the space between the sections.

H1 should be reduced so that it is smaller than the topic title but still bigger than H2

![IMG_68632717B30C-1](https://user-images.githubusercontent.com/21990736/137412525-ac152309-76a8-40db-9e46-cd543fb0f2f1.jpeg)
)

**Comment by deniza-pg** [comment]
@cherrielam  can you test if this is working?

**Comment by cherrielam** [comment]
Yes! It is working on Staging.
