### ISSUE TITLE
Improve visual consistency between onboarding and questionnaire

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1828]
With recent changes to the flow the first time a user uses the app, the questionnaire now follows directly from the onboarding. Both contain similar UX elements, but they are styled differently, which is more apparent due to how they now run one right after the other.

### Acceptance Criteria 
- [ ]  Onboarding and questionnaire visual elements are consistent

**Comment by alysha-PG** [comment]
Suggested update for this:
Leave onboarding buttons as they are (teal/green background with white text). Update questionnaire buttons to be consistent with onboarding. So instead of questionnaire buttons having a white background with a teal/green outline, make them teal/green background with white text. Please consult @Juancorrea22-pg 's eyes for visual consistency when you are working on this issue.

**Comment by rasmus-storjohann-PG** [comment]
- [ ] Move questionnaire buttons all the way to the left/right edge.
- [ ] Change the onboarding buttons so that all the buttons have the same font size and the same button height
- [ ] White background for Back and Skip, and dark colour on the Next
- [ ] Move the questionnaire buttons down a bit
