### ISSUE TITLE
BC English content: Housing-Utilities 

### ISSUE THREAD

**Issue by Meaad-PG** [pg-irc/pathways-frontend#1938]
I see this unnecessary text that I don't see in UK content. 
![IMG_4136](https://user-images.githubusercontent.com/102553427/169219297-0450df2a-49a5-4137-bb2b-5855d383145b.jpg)

**Comment by rasmus-storjohann-PG** [comment]
This one is interesting, what I thought was totally valid markdown for an email address does not show up correctly in the app. @alysha-PG thoughts?

**Comment by alysha-PG** [comment]
The valid markdown does work in lots of other places, so there are 2 things I think might be happening here-

1. Because the fact the email is clickable, it seems like there is working markdown within it, so maybe in the MD it has a repetition of markdown where it actually looks like this with no spaces- 
> [Email: [HSRTO@gov.bc.ca] (mailto:HSRTO@gov.bc.ca) ] (mailto:HSRTO@gov.bc.ca)

2. The bracket before Email should actually be before the address rather than the word email, so that's making what is in the parentheses show up? So try moving the bracket and see if that works?
But then I don't know why it is working, unless the app just magically makes emails clickable and I didn't need to go in and manually fix all of those.......

**Comment by alysha-PG** [comment]
not fixed

**Comment by alysha-PG** [comment]
Ok the link is working now but the word "Email:" got erased, and should go back in. Third time's a charm?

![File.jpg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/5e4ea84c-306d-41e6-b7f8-113c824246a1)
