### ISSUE TITLE
Figure out versioning for client and server

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#297]
ACs: Have a plan for how we will use versions for user testing, git, server, client, etc

Update: This is mostly done, one last, optional piece is to have the server version string appear in the client About box, this would be all client side to make the network call and show the returned string on the screen.

**Comment by robinpuga** [comment]
You should take a look at 	https://semver.org/

**Comment by rasmus-storjohann-PG** [comment]
# Suggested rules: 
* Client and server are versioned independently.
* Client specifies the minimum server version required for proper client operation.
* We use [semantic versioning](https://semver.org/) of the form X.Y.Z
* Versioning happens at the end of each sprint.
* We bump the Z each sprint, except for sprints where no changes went in
* We bump the Y when we add features that are backwards compatible
* We bump the X when we add features that are backwards incompatible, i.e. when the client would fail to operate correctly with an older server version.
* Versions are stored as tags on the master branch in git, as well as in [__init__.py](https://stackoverflow.com/a/16055291) on the server and in [package.json](https://docs.npmjs.com/files/package.json#version) on the client.

# Questions?
When would we ever bump X on the client?

**Comment by bensinjin** [comment]
@rasmus-storjohann-PG Using Release Channels will likely be related to this work: https://docs.expo.io/versions/latest/distribution/release-channels

**Comment by rasmus-storjohann-PG** [comment]
@robinpuga for review, or if you don't have time, let me know

**Comment by rasmus-storjohann-PG** [comment]
@bensinjin for review and feedback with specifics on release channels, avoiding accidental push of dev builds to production, etc.

**Comment by robinpuga** [comment]
@rasmus-storjohann-PG This looks pretty good to me. Thanks for pulling this together. I think it would be good to include these Rules in both project's ReadMe files or wherever seems appropriate. 

I would also add a note for Hotfixes (emergency deployments outside of sprints) for both the client and server. These should also bump the Z value. 

RE: When to bump the X on the client? I would say this would be bumped when major API changes to the server happen which means it is no longer compliant with previous versions of the server. Additionally, there may be times we want to bump the X for marketing purposes because MARKETING!

**Comment by rasmus-storjohann-PG** [comment]
TODO: Make a postinstall script on the client to validate that the version id in package.json, app.json and VERSION.txt all match. Something similar can be done on the server.
