### ISSUE TITLE
Local storage infrastructure

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#36]
ACs: Describe persisted entities and their properties, remaining agnostic to SQL or key/value storage
* Questions + optional responses
* Tasks, all tasks in my task list are available off line.
* Tasks completed.
* User ordering of tasks.
* Services for a task.
* Starring of tasks.
* Deleted tasks: user removed from task list.
* Task annotated with taxonomy term
* Task importance / urgency.
* User language settings.
* User access token.
* "Don't show this again" state for various popups
* Migration, validation to ensure that migration worked correctly.

library choice: redux-persist or expo-sqlite. 
UX: consider spotify UX for downloading content for offline access

**Comment by tnightingale** [comment]
I have briefly looked into commonly used mobile/React Native storage options. Unfortunately there isn't much. Redux-persist seems to be the most common choice among React Native devs (clearly they're all also using Redux).

The other frequently mentioned options are:
- [Expo SQLite]
- [react-native-sqlite-storage]
- [Realm]
- [Firebase]
- [PouchDB]/[Couchbase Mobile]

### [Expo SQLite](https://docs.expo.io/versions/latest/sdk/sqlite)
**Pros:** 
Full access to sqlite database, referential integrity, transactions
**Cons:** 
No support APIs, eg: migrations, querybuilder, etc
**Notes:**
[Migrations are potentially not too hard to implement ourselves](https://github.com/litehelpers/Cordova-sqlite-storage#database-schema-versions) (example comes from the Cordova version of react-native-sqlite-storage).

I also looked at http://knexjs.org/ as a way of providing some support. There are a couple examples of people using it in React Native with both Expo SQLite & react-native-sqlite-storage. Unfortunately it's fundamentally built for a nodejs/server/non-mobile environment and requires a slew of nodejs polyfills. The migration & seeding functionality assumes CLI & filesystem access so likely isn't very useful to us.

### [react-native-sqlite-storage]
**Pros:**
Same as Expo SQLite
**Cons:**
Same as Expo SQLite but also requires us to eject from CRNA and install manually with some non-trivial, platform-dependant steps ([iOS](https://github.com/andpor/react-native-sqlite-storage#how-to-use-ios) & [android](https://github.com/andpor/react-native-sqlite-storage#how-to-use-android))
**Notes:**
Same as Expo SQLite

### [Realm]
**Pros:**
Referential integrity, mandatory transactions, object-orientated (not ORM) storage, FRP-style (functional-reactive-programming) API (observables, events, etc), migrations API.
**Cons:**
Closed-source, not SQL (Realm created their own database), young project.
**Notes:**
Very interesting project, fully featured database, closest self-hosted competitor to [Firebase].

### [Firebase]
**Pros:**
Built-in data synchronization with Firebase/Google's server offerings.
**Cons:**
Closed-source, not SQL, remote data lock-in, privacy implications (Google)?
**Notes:**
I suspect this is a non-starter because Google

### [PouchDB]/[CouchBase Mobile]
**Pros:**
Built-in data synchronization with CouchDB
**Cons:**
Not SQL, Document store (limited/no relational data), PouchDB requires underlying storage (SQLite), No migrations
**Notes:**

[Expo SQLite]: https://docs.expo.io/versions/latest/sdk/sqlite
[react-native-sqlite-storage]: https://github.com/andpor/react-native-sqlite-storage
[Realm]: https://www.realm.io/
[Firebase]: https://firebase.google.com/
[PouchDB]: https://pouchdb.com/
[CouchBase Mobile]: https://www.couchbase.com/products/mobile

**Comment by tnightingale** [comment]
Based on the above, I'm leaning towards just running with redux-persist until (if?) it becomes a problem.

🤷‍♂️

If we want something else, we either build our own support API on top of Expo Sqlite or build on top of Realm (which carries potentially significant risk/unknowns).
