### ISSUE TITLE
Typo in disclaimer

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#498]
**Describe the bug**
Typo in the disclaimer.

**Linguistic issues**
- Current text: Utlization of services located through the app is undertaken as the risk of the user.
- Suggested text:  Utilization of services located through the app is undertaken as the risk of the user.
- Reason: typo in English

![screenshot_20190224-130228_arrival advisor](https://user-images.githubusercontent.com/44411551/53305401-1b5d4e80-3836-11e9-97da-994f3b78afcb.jpg)

**Comment by rasmus-storjohann-PG** [comment]
The string in localized using lingui. Changing the English will cause ripple effects through the other localization files. When solving this issue, we need to (1) ensure that the translation of the affected string into other languages is not broken, and (2) carefully document the process, since this will not be the last time we need to make this change. This case is simpler than most, since the change in the English will not trigger the need to update the translation in other languages, so it makes for a nice test case for just the localized string management.

**Comment by rasmus-storjohann-PG** [comment]
Fixed as part of a PR that also addressed #529
