### ISSUE TITLE
BC211 : Service missing address

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#506]
Service listing that do not have an address appear at the top in the recommended services list. 
Need to figure out the best way to handle services with no addresses. 
![screenshot_20190227-172017_arrival advisor](https://user-images.githubusercontent.com/44411551/53534538-186f9180-3ab4-11e9-8062-20cf9a635513.jpg)

**Comment by ArtiBPG** [comment]
Next steps:
- Figure out if the lat long pair is missing from BC211 database
- Should we add a note to explain why address is missing: intentional or just missing

**Comment by ian-lin-PG** [comment]
I took a look at this particular service listing. There is no address or phone numbers provided, only a url. My guess is that there is no physical office and most of the activities are organized online. 

The lat lon is available, but looking up on google maps shows a residential street. It could be someone's home office, but unlikely a visitable location.

**Comment by ian-lin-PG** [comment]
In my test, confidential phone numbers are not screened out. Out of all the services there are 29 instances of 'Confidential="true"', they can be mailing addresses, physical addresses or phone number. Proportionally speaking, users are highly unlikely to run into these contact informations, but it is possible.

**Comment by ian-lin-PG** [comment]
In summary, lat lon appears to be a required field for submission to bc211 but not physical address. It may be possible for a service to show up as a result despite not having an address. 

Addresses can be intentionally missing, as in the case of the screenshot, where a physical location is not available because the services are mostly online.

There are 29 instances of  'Confidential="true", of which 5 of them are phone numbers. We can certainly screen the confidential phone numbers, but it's unlikely for the users to com across them.

**Comment by ArtiBPG** [comment]
@ian-lin-PG can you write up next steps.

**Comment by ian-lin-PG** [comment]
@rasmus-storjohann-PG There are some fields that have an option 'Confidential="true"' like:
![image](https://user-images.githubusercontent.com/52009863/62653724-03c0e080-b913-11e9-9a3d-b5b18c8b9b37.png)
Can we check with bc211 to see if these are left in by mistake? We might also make another issue to stop the parser from parsing information labeled as confidential.

**Comment by ian-lin-PG** [comment]
We have a new issue pg-irc/pathways-backend/issues/419 to address fields that are labeled 'Confidential="true"'.

**Comment by ArtiBPG** [comment]
I'll close this as it is being dealt with in pg-irc/pathways-backend/issues/419
