### ISSUE TITLE
App store description has typos and incorrect website address

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#514]
Text in the app store description needs to be fixed and updated with the right information.
Related to [512](https://github.com/pg-irc/pathways-frontend/issues/512)

**App version**
Version 1.0.7

Fix the website address from the peacegeeks site to the arrival advisor site.

![image](https://user-images.githubusercontent.com/32307781/53828688-382f0b80-3f33-11e9-8057-884141e1fd41.png)

![image](https://user-images.githubusercontent.com/32307781/53828783-762c2f80-3f33-11e9-9507-50edb070bd74.png)

**Comment by cherrielam** [comment]
@ArtiBPG @rasmus-storjohann-PG Not sure where the small description came from, I reckon the App Store people wrote it.
*old*: Guide to the newcomer experien
*new*: For newcomers to BC, Canada

(My suggestion ^)

@ArtiBPG Because this wasn't written by Lauren or I, this does not exist in the spreadsheet. Please add.
