### ISSUE TITLE
Translation of dynamic content

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#59]
AC: When switching language, dynamic content appears in appropriate language.

Fixture needs to be populated with stubbed multilingual content

**Comment by tnightingale** [comment]
I'm proposing we add a new type for translated content in our data model:
```typescript
interface LocalizedText {
    [localeCode: string]: string
}
```
I will use Task as an example:
```typescript
interface Task {
    readonly const id: Id;
    readonly const name: LocalizedText;
    readonly const content: LocalizedText;
    readonly const isRecommendedToAllUsers: boolean;
    readonly const isStarred: boolean;
    readonly const isComplete: boolean;
}
```
A representation would now look like this:
```json
{
    "id": "12345",
    "name": {
        "en": "the task name",
        "ar": "اسم المهمة",
        "zh": "任務名稱"
    },
    "content": {
        "en": "the task content",
        "ar": "محتوى المهمة",
        "zh": "任務內容"
    },
    "isRecommendedToAllUsers": false,
    "isInMyPlan": false,
    "isStarred": false,
    "isComplete": false
}
```
With this model we need to perform a transformation on all LocalizedText fields, something like:
```js
function selectLocalizedText (locale: Locale, localizedText: LocalizedText): string {
    return localizedText[locale.code]; // TODO: handle fallback locale (eg: via something like locale.default)
}
```

There are two options for where this transformation could occur:
1. During component render (the component would also require locale info eg: current locale code and, if supported, fallback locale).
2. During data fetching from store, for eg: in a selector (it would first get locale info from elsewhere in the store).
 
Option 1 requires getting the current locale from somewhere, either by fetching it from our store (using a selector and a connected component somewhere in the component tree) or fetching it from jsLingui's `I18n` context object (we would need to wrap relevant components with jsLingui's `withI18n` HOC).

Option 2 implies a second type for all of our localizable entities:
```typescript
interface LocalizedTask {
    readonly const id: Id;
    readonly const name: string;
    readonly const content: string;
    readonly const isRecommendedToAllUsers: boolean;
    readonly const isStarred: boolean;
    readonly const isComplete: boolean;
}
```

_I am currently leaning towards option 2 as it keeps the localization logic out of our components as much as possible._

In my opinion, both of these options have a downside; they result in localization logic being sprinkled throughout our application. Almost everything UI-related will need to concern itself with first determining the current locale and ensuring the appropriate transformations have been made. The counter argument is that UI code already needs to consider locale due to rending of static messages. However I believe that static messages are far less complicated than localized content and their implementation is already well-handled with 3rd-party code (jsLingui).

**Comment by rasmus-storjohann-PG** [comment]
Thanks for the writeup, it's nice and clear.

As you do, I much prefer option #2. It's very normal that the selectors return data in a different form from what is sitting in the store. E.g. it will almost always be the case that data in the store are normalized and the data from the selectors are not. Also, since we have decided that all selectors take the entire Store as argument (so that no code outside of selectors need to know which store substructure to pass in), it follows that all selectors pulling localized data out of the store can access the current locale from the store. So no code outside of selectors should need to worry about the current locale. I think this will actually be pretty tidy.

As long as the locale doesn't change (which is most of the time), we should be able to use reselect to cache localized content so that there should be no performance hit from localization either.
