### ISSUE TITLE
Plan search

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#654]
Description:
Scope and design search feature.

Search spec and research:
https://docs.google.com/document/d/1alwa7mx1_av2_Sc24t3VnlRwOu71pNGr5y1CBsCM3oc/edit#heading=h.86ql1cvdy419 

Next steps:
- Final mocks

**Comment by cherrielam** [comment]
Mocks will be available by Monday - they will be iterations of these: https://github.com/pg-irc/pathways-ux-ui/issues/55

**Comment by cherrielam** [comment]
@ArtiBPG As discussed on Thursday, I will be planning for some testing of the multilingual configuration on the app screens, and also amending the "Services at this organization" part, but otherwise @rasmus-storjohann-PG can definitely start planning for development of the other parts unless you want more testing

**Comment by rasmus-storjohann-PG** [comment]
Closing this issue as redundant, see https://github.com/pg-irc/pathways-backend/issues/423
