### ISSUE TITLE
Update expo

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#687]

**Comment by rasmus-storjohann-PG** [comment]
Test 
   * fooo
test

**Comment by ian-lin-PG** [comment]
I upgraded @types/react and @types/react-native by setting the floor to be the version released 3 months ago around the react-native .59 release. Yarn resolved the dependency to be the newest versions of both libraries. 

There's only 1 minor change with the KeyExtractor function, otherwise all the tests passed and manual QA did not reveal any new issues. 

I can confirm it's the correct version of react-native because I was able to use maxFontSizeMultiplier which is a new feature present at the .59 release.
