### ISSUE TITLE
Change link text on About page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#700]
ACs:
* Change link text from "view it on Github" to just "Github".
* Update English text so that "view it on" is part of the text, not the link.
* Review whether similar changes need to happen in other locales. Abdi tells me that no change needs to be made to the Arabic text.

**Comment by rasmus-storjohann-PG** [comment]
![image](https://user-images.githubusercontent.com/32307781/60617294-4c233680-9d88-11e9-85ca-5f0d21b3e58e.png)

**Comment by bensinjin** [comment]
Waiting on feedback for: https://github.com/pg-irc/pathways-frontend/pull/723 as this will build on that.

**Comment by tomy-pg** [comment]
AC:
Update the link in:
- [ ] Arabic
- [ ] French 
- [ ] Punjabi 
- [ ] Chinese Simplified
- [ ] Chinese Traditional
- [ ] Tagalog

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server V1.3.9 on iOS and confirmed for English:
- [x] Changed link text from "view it on Github" to just "Github".
- [x] Updated English text so that "view it on" is part of the text, not the link.

![IMG_2372](https://user-images.githubusercontent.com/48343061/64995871-3c989180-d891-11e9-8de2-cfefcaa4c39e.JPG)

- [x] Arabic
![IMG_2373](https://user-images.githubusercontent.com/48343061/64995860-35718380-d891-11e9-8c75-842faf920fa9.JPG)

- [x] French
![IMG_2382](https://user-images.githubusercontent.com/48343061/64995895-4de19e00-d891-11e9-8b03-7b3d6716bf9c.JPG)

- [x] Tagalog
![IMG_2377](https://user-images.githubusercontent.com/48343061/64995939-694ca900-d891-11e9-8dfd-0a164fec0577.JPG)

- [x] Punjabi
![IMG_2376](https://user-images.githubusercontent.com/48343061/64995983-85e8e100-d891-11e9-8f8a-901abdb2004f.JPG)

**Comment by jparlina** [comment]
Tested on Staging V1.4.0, Server V1.3.9 on iOS:
The following need spaces (marked in red on screenshots) before and/or after the link(s) for 
- Korean: missing a space **_after_** "Github"
- Chinese Simplified: missing **_before_** and _**after**_ "Github", as well as **_before_** and **_after_** "Newcomers Guide to British Columbia"
- Chinese Traditional: missing **_after_** "Github", as well as _**before**_ and **_after_** "Newcomers Guide to British Columbia"

![IMG_2380](https://user-images.githubusercontent.com/48343061/64996469-e4fb2580-d892-11e9-9338-15979866152a.JPG)

![IMG_2379](https://user-images.githubusercontent.com/48343061/64996543-1116a680-d893-11e9-8a1b-d92a55a0cc4f.JPG)

![IMG_2381](https://user-images.githubusercontent.com/48343061/64996534-0bb95c00-d893-11e9-9f4f-09a3640b21d1.JPG)

**Comment by jparlina** [comment]
@ian-lin-PG Could you please look at the missing spaces as noted above? Thanks

**Comment by ian-lin-PG** [comment]
@jparlina I am not familiar with Korean but can give feedback on the Chinese. There are usually no spaces in between characters in Chinese, so spaces does not impact the meaning of words in Chinese as it does in English. We can change the translations so we are more disciplined in weaving English within Chinese.

**Comment by jparlina** [comment]
Thanks @ian-lin-PG! I'll move this to "Ready for production" then.
