### ISSUE TITLE
Metrics: Make a separate Google Analytics id for the staging app

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#707]
So that analytics for the production app and staging app can be kept separate.

**Comment by tomy-pg** [comment]
New id for Staging. 
To be done for next week's (August 8, 2019) Staging Release.

**Comment by rasmus-storjohann-PG** [comment]
Created the new property, the id to use for staging is UA-30770107-5

**Comment by tomy-pg** [comment]
Client: 1.1.0 / Server: 1.3.5

Confirmed. Seeing real-time analytics with the new staging id.

**Comment by ArtiBPG** [comment]
Analytics bug:
-Analytics for v 1.3.0 (probably debug app as this version has not been released yet) shows up
- Analytics for 1.0.13 when used at the HiVE shows up on the IP excluded page.
Screenshot: https://screencast.com/t/x7HW1M1p

AC:
- Analytics from staging and debug builds should not show up 
- Analytics from phones in the HiVE should not show up on the IP excluded report.

**Comment by ArtiBPG** [comment]
related #742

**Comment by tomy-pg** [comment]
@ArtiBPG for the issue of analytics from staging and debug being shown from the production Google analytics here is what Ian and I have found in our investigation:

- by default the GOOGLE_ANALYTICS_TRACKING_ID in our `.env` file is set to the ID for our ArrivalAdvisor (Production) app. We are seeing our EXPO activity on our Google analytics because of this. Our staging and debug apps are not being shown because we are setting the Analytics Tracking ID to something different. 
- the reason why you saw version 1.3.0 is because in the app.json file we had 1.3.0 as the version in master: https://github.com/pg-irc/pathways-frontend/blob/master/app.json

How to avoid this: Make sure we are not pointing to the Google Analytics ID for ArrivalAdvisor(production) in our `.env` files

**Comment by tomy-pg** [comment]
We have Google Analytics to anonymize IP Addresses. The catch to this is that we cannot then use filters to exclude IP Addresses since we do not know which IP Address the user is on. A work around to this is coming shortly.

**Comment by tomy-pg** [comment]
In regards to "Analytics from phones in the HiVE should not show up on the IP excluded report."
I have created a Segment that is able to be applied to future and retroactive Google analytics data. I am not including analytics from The HiVE's ISP: Urban Networks Inc.

If there is something else I can add to this Segment let me know.
