### ISSUE TITLE
BC Newcomers Guide - dead links

### ISSUE THREAD

**Issue by jparlina** [pg-irc/pathways-frontend#800]
Tested on both Production V1.0.13 Server 1.2.3 and Staging V1.2.0 Server 1.3.8 on iOS:
the link in the third paragraph under the topic "Distributed (distance) learning and homeschooling for children" no longer works - see screenshots below.

To discuss with team as part of AA maintenance - to test links from BC Newcomers Guide and BC211 periodically? 

### Acceptance Criteria 
- [ ]  Link should direct you to the right page 
- [ ] App should correctly handle links embedded in Chinese text, including cases where the url is immediately followed by Chinese space, comma or full stop characters.

Examples of dead links (see screenshots below):
- Education > Distributed (distance) learning and homeschooling for children > link in paragraph 2 
- Education > Early years programs for children under five years of age > links in paragraphs 2 and 3

![IMG_2274](https://user-images.githubusercontent.com/48343061/64466744-7535af80-d0c8-11e9-9726-03fc30692971.JPG)

![IMG_2284](https://user-images.githubusercontent.com/48343061/64574480-811dad80-d324-11e9-9411-debb105d6e58.JPG)

![IMG_2275](https://user-images.githubusercontent.com/48343061/64466746-7961cd00-d0c8-11e9-86cf-31df55c25462.JPG)

**Comment by rasmus-storjohann-PG** [comment]
The Plan:
- [ ] Review `pathways-frontend/src/fixtures/newcomers_guide/tasks.ts` for broken links, compile a list. This will include links in the Chinese and other languages where links are followed by unicode characters. Known examples include Chinese comma and full stop, but there are others.
- [ ] Write unit tests specifying the correct mark-down for these links
- [ ] Refactor client code so that `/pathways-backend/utility/extract_all_urls.py` and `/pathways-backend/newcomers_guide/clean_data.py` both use the same regular expression to find links
- [ ] Update that shared regular expression to make the unit test pass.
- [ ] Use the extract script to pull all (really all this time) urls from the content, and check for dead links.
- [ ] Update the spreadsheet with any missing live links
- [ ] Run the update script to update all NCG content with good links
- [ ] Check in the updated content
