### ISSUE TITLE
Build search input screens

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#838]
[User Stories](https://github.com/pg-irc/pathways-frontend/issues/841)

ACs:
- [ ] Search screen, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa4bb3cda171b4e0dbc). Clicking to focus on to upper search line opens the Search string input screen. Clicking to focus on to lower search line (location) opens the Search location input screen.  
- [ ] Search string input screen, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa44f3ff161cec799ad). Clicking return takes user back to the Search screen populated with search results.
- [ ] Search location input screen, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa42db2bc777d20277d). Clicking return takes user back to the Search screen populated with search results.

* Component "Why is some information in English?" is OUT OF SCOPE for the thin thread.

**Comment by ArtiBPG** [comment]
@cherrielam test on Android and iOS

**Comment by ArtiBPG** [comment]
@cherrielam the search input feel a bit awkward
Users have to click on search>go to inout screen>go back to search>click on location>enter location>then results show up.
Can we just let users enter search query and location on the search screen itself: https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa4bb3cda171b4e0dbc

**Comment by cherrielam** [comment]
A few issues. Let me know if these should be addressed in other issues 😄 

### Bugs 🐛

**UI** 

- [ ] Search for services and City, address, or postal code should be in Avenir (both on the main page and the modal page) [Screenshot for reference](https://drive.google.com/open?id=1xyadfGo5hXcmmk10ejdWMInupmu5Yq7f)
- [ ] Search bar text should be pushed down a little to be vertically aligned with the icons
- [ ] Search is too close to the top bar [Screenshot for reference](https://drive.google.com/open?id=1HvN1_TfOIVJtNmxFaXLQrftfhfq7kBmP)



**UX**

- [ ] Search results should be empty if no keyword is entered and no location has been entered. @rasmus-storjohann-PG to get back to us as to what is technically possible, and then @aron-chen-pg and I should revisit empty search state

- [ ] Related to above: Presently it is possible to search a keyword without entering a location. This seems strange because it is unclear where the services are sorted from. Recommended UX flow is as follows: 

          1. User opens the Search page or any Services Listing page for the first time. 

          2. User is asked if they want to turn on location services (via native alert). 

          Instead of being prompted on opening the Search/Services Listing page,
          this can also be done on initial app open.

          3. IF user selects to Turn On Location Services, the app defaults the location
           of Search to "Near my location". 
          IF user selects to Not Allow Location Services, the app leaves the location of 
          search to empty - "City, address or postal code"

          4. IF location of search is empty, the empty search state (no keyword,
          no location) should return no services (as mentioned above). The user can
           enter a keyword, but so long as the location is empty, the search should not 
          return results. Entering a keyword without a location should prompt the user 
          to enter a location. 
         (See video of similar experience on MindBody App linked below)

          5. The search only runs once the keyword is filled AND the location is filled.

   ^ See [video of similar experience on MindBody App](https://drive.google.com/open?id=1RSABezrkIPT4u4lh2mLhwX_J6OOnR2EP)

- [ ] Pressing the back button when a search term is entered but not submitted should not run the search. (See [video of current AA behaviour](https://drive.google.com/open?id=1dw7BBYQYDgugrdfYU20cb_8TUuuksFVx) — here, I enter "employment", and then press back. This still submits "employment", which is not what is supposed to happen. Going back should clear typed-in search (to previous search), not run the typed-in search. Here is a [video of what happens in Google Maps](https://drive.google.com/open?id=1L8XPWTHXVxQibrj4pvysDezb8dD3c-_b). Google Maps shows the correct behaviour.)

- [ ] Keyboard behaviour. On **iOS**: the bottom right button on the native keyboard should say "Submit" on the search modal, instead of "Return". When the search bar is empty, the "Submit" should be grey (not clickable). When the search bar is filled, the "Submit" should be blue (active). (See correct behaviour in Google Maps example on iOS). On **Android**: the bottom right button on the native keyboard should show the Search icon, instead of "Done". (See screenshot of keyboard on Google Maps search on Android)

- [ ] Back button on the page. Currently clicking the Back button when a search has been entered takes the user to the home screen. Clicking the Back button should **clear the search**, not take the user to a different page. There **should not** be a back button on the search when the search is **empty**.

- [ ] Need an error state if a keyword was not found. Currently it is empty. [Screenshot for reference](https://drive.google.com/open?id=1lBzSQjggdPSfbreraPYCIA3e4b-y6y8N) @aron-chen-pg has mocked this (see: https://github.com/PeaceGeeksSociety/pathways-ux-ui/issues/107), will be moved to frontend repo soon.

- [ ] Search still returns when a location is wrong/does not exist. This should not happen. Invalid locations should return error state. [Screenshot for reference](https://drive.google.com/open?id=14BNVHSTVwXccXjNAj4uvmrrFlJaxnjAO) (Error state mock is here: https://github.com/PeaceGeeksSociety/pathways-ux-ui/issues/107 - this will be moved to frontend repo soon)

**Performance**

- [ ] Appearance/disappearance of the X when search term is typed/empty feels a big laggy
- [ ] Once a search is entered, there is a lag for it to load (from the modal screen back to the main screen). Can we get the modal to close immediately and to add a loading spinner to the main screen to indicate to the user that the search is loading?


### Discussion

- Should the search run if there is a location set, but NO keyword? I'm not sure... thoughts? (@aron-chen-pg @rasmus-storjohann-PG)
- Can we auto-fill locations when the user starts typing a location into the search? (@rasmus-storjohann-PG )
- What is the distance by which the services are shown? (@rasmus-storjohann-PG) How do we make this more obvious for users? (@aron-chen-pg @cherrielam to work on)

**Comment by ArtiBPG** [comment]
> 
> ### Discussion 🤔
> * @ArtiBPG the awkwardness is a bit of a performance issue, esp. noticeable since it takes so long for the search to load. But the current flow is actually quite similar to apps like (I linked videos of the screen flows: ) [Google Maps](https://drive.google.com/open?id=1_Rm9MaA0X7m-F9IQfbVz2_lXdwYSN6rz), [Eventbrite](https://drive.google.com/open?id=1GlfY54OuXGogs3sSXU0fKWASF06kPPdL), [Airbnb](https://drive.google.com/open?id=1oZK-IOUjIbR3jH5oTJOoiTPMwKmBE2Jx), [App Store](https://drive.google.com/open?id=1HSp4rbZP1oA526h9Q4smwYPqGzlVChSO), etc. where each search input, once clicked, changes to its own "search active" page to accommodate for more space for the keyboard. An alternative might be if we do it something like the [Mindbody app](https://drive.google.com/open?id=1baMhCAkhvgPFKr2UV3yG9eGnpWxd9pki), where the search bar is smaller and expands to show both inputs on the active page? This might be a good idea to make the search more "space saving". Thoughts? @aron-chen-pg
> * Should the search run if there is a location set, but NO keyword? I'm not sure... thoughts? (@aron-chen-pg @rasmus-storjohann-PG)
> * Can we auto-fill locations when the user starts typing a location into the search? (@rasmus-storjohann-PG )
> * What is the distance by which the services are shown? (@rasmus-storjohann-PG) How do we make this more obvious for users? (@aron-chen-pg @cherrielam to work on)

@cherrielam I think the Mindbody app example is the only one closest to our application, if we start here: https://screencast.com/t/Dfs2Hlib
Also I don't think we we need to auto-fill locations at this time. If its easy to do, then ok but is not necessary.

**Comment by rasmus-storjohann-PG** [comment]
@ArtiBPG I think we can just close this story, since we're going over the whole search UX again.
