### ISSUE TITLE
Organization & service details page

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#842]
* Page [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5e4bb44026858ebbf).
* Service tab using the service list component as elsewhere. Is it OK to use the same list component in so many places? Could be confusing to the user...

---
ISSUE HAS BEEN UPDATED by @cherrielam (Nov. 13, 2019). Please refer to below -
> Because the **Org Detail** and **Service Detail** pages are very similar, I recommend that this issue involve creating the UI for both.
> 
> ### Mocks
> Org detail page: https://zpl.io/2G13xKd
> Service detail page: https://zpl.io/2j7doNq
> To see the whole flow: https://sketch.cloud/s/jeZG7/a/qaE2gn/play
> 
> **Differences between Org Detail and Service Detail**
> 
> * **Service Detail** has "Provided by [ORG]" section in its layout
> * **Org Detail** has two tabs, one screen with About the org (Detail page) and one screen with its services
> 
> ### Important notes on developing this issue:
> * Because this issue is intended to be for the _Search thin thread implementation_, I recommend reusing the bookmark icon that is currently used for Topic Detail, instead of creating the "Save service" button currently shown in the mocks.
> * Bookmark applies to services only, not orgs
> * The top image on an org is supposed to be something like a Logo... feel free to leave out in this implementation.
> * This issue doesn't deal with the top nav content as that depends on where the user comes from, and has bigger technical complications... should be split to a separate issue
> * There is a new light grey colour used on the screen, which is inconsistent with the Topic Detail. Use the old Topic Detail beige colour for now, we can review the UI and tweak once it's viewable in the app

### Testing
Because we don't actually yet have orgs and services in the app the best way to see these screens in their current state is as follows:

1. edit `src/components/main_page_switcher.tsx` around line 44, in the `defaultPath` function add: `return routePathWithParameter(Routes.ServiceDetail, 'testing');` (you'll need to import this function) as the first line, this will load the new service detail screen as the first screen once Expo reloads app.
2. Check the "Provided by" link from the Service detail takes you to the Organization detail screen
3. Show screens to Cherrie and provide feedback on the PR

**Comment by bensinjin** [comment]
Updated mocks: https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5e4bb44026858ebbf

**Comment by bensinjin** [comment]
Also, Cherrie suggests we just reuse the existing bookmark in the top nav as apposed to the button for now.

**Comment by cherrielam** [comment]
Because the **Org Detail** and **Service Detail** pages are very similar, I recommend that this issue involve creating the UI for both.

### Mocks
Org detail page: https://zpl.io/2G13xKd
Service detail page: https://zpl.io/2j7doNq
To see the whole flow: https://sketch.cloud/s/jeZG7/a/qaE2gn/play

**Important notes about developing this issue:**
- Because this issue is intended to be for the _Search thin thread implementation_, I recommend reusing the bookmark icon that is currently used for Topic Detail, instead of creating the "Save service" button currently shown in the mocks.
- Bookmark applies to services only, not orgs
- The top image on an org is supposed to be something like a Logo... feel free to leave out in this implementation.
- This issue doesn't deal with the top nav content as that depends on where the user comes from, and has bigger technical complications... should be split to a separate issue

**Differences between Org Detail and Service Detail**
- **Service Detail** has "Provided by [ORG]" section in its layout
- **Org Detail** has two tabs, one screen with About the org (Detail page) and one screen with its services

**Comment by bensinjin** [comment]
We noticed some of the colors weren't consistent with the existing Topic screens, Cherrie says to keep things consistent for now and we'll revisit tweaks once it's viewable in the app.

**Comment by rasmus-storjohann-PG** [comment]
Reviewed issue, looks good. @cherrielam FYI.

**Comment by cherrielam** [comment]
As per my conversation with @bensinjin, there is no way to access the _Organization Detail_ page on Staging currently, so I am just QA'ing the _Service Detail_ page assuming both will be the same.

#### Notes from QA on both iOS and Android - need to be addressed:

- Organization name should **not** be in All Caps, just regular case. (I think there was confusion here because in the example, "MOSAIC" was in all caps, but that's because the name itself is capitalized inherently).
- Organization name should not be underlined. (Just bold and teal to indicate link is fine)
- Currently, if the address/website or similar field is too long, the icon gets pushed to the right. This should not be the case. The text should wrap downwards rather than pushing the icon. The icons should stay vertically aligned with each other. See below:

![IMG_7451](https://user-images.githubusercontent.com/21990736/71378038-27f82380-257b-11ea-86f6-a45fcc01858e.PNG)

![Screenshot_20191220-160549_Arrival Advisor](https://user-images.githubusercontent.com/21990736/71378029-1b73cb00-257b-11ea-8a2f-65afbd98b2bc.jpg)

- Final recommendations: If the Detail page is to be released to production before we are able to an image or map at the top, I would hide the default header (hide the part with the AA icon)

**Comment by rasmus-storjohann-PG** [comment]
Closing this issue, completion of this functionality is planned in #1042
