### ISSUE TITLE
Services load slowly on iOS

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#861]
The loading time for services listing is currently quite slow on iOS, and this is a performance issue. It needs to be faster on iOS

### Difficulty, impact:
|--(technical difficulty = ??)--| -- high user importance (SHOULD have) -- |

### Acceptance Criteria:

- [ ]  Subsequent loads of services are quicker

**Comment by ArtiBPG** [comment]
Does it seem slow on Android?

**Comment by bensinjin** [comment]
To improve performance we suggest the following:

ACs:
- Add `expiresAt` property to `servicesForTopics` object in the store
- When topic services are fetched from the server we update `expiresAt` to the current time plus one day
- The topic services component does not hit the server if there are unexpired topic services available

**Comment by tomy-pg** [comment]
@bensinjin can we get steps for QA on this issue?

**Comment by jparlina** [comment]
Tested on Staging V1.16.0 using iOS 7s at the HiVE: 
It takes about 9-12 seconds to load services. Discussed with @cherrielam, we both think it's still slow. Is it technically possible to cut the load time in half for better user experience? 

@bensinjin Is there a benchmark for acceptable loading time?

**Comment by bensinjin** [comment]
So the original work actually is in place to speed up subsequent request, not the initial request, I did some digging however and think we can use another API to improve the initial fetch which is actually slow due to the time it takes to find your location. See: https://github.com/pg-irc/pathways-frontend/pull/1003

Testing instructions:

- [ ] Initial services fetch is faster
- [ ] An appropriate level of "distance" accuracy is achieved

**Comment by jparlina** [comment]
Tested on Staging V1.22.0, server V1.3.24 on iPhone 7s at the HiVE - PASSED

Testing instructions:
- [x]   Initial services fetch is faster
- [x]   An appropriate level of "distance" accuracy is achieved
