### ISSUE TITLE
Keyword search polish: Build split keyword/location text entry field

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#938]
See commit ac1c03eb14821a73632b415fcceb2735382913e6 and those preceding it, I had something like what is described here working, so there might be some ideas to be had.

**1.** Split search into two input fields. With the aim to allow users to search conveniently, we want to provide an updated search experience where users could adjust both the keyword and the location field together instead of having to navigate between one to another. Users may optionally specify location, so search works with or without location set.

Search is not "live", user has to click button "Search" (in upper right of mocks) to make the search happen. 

Stretch goal is to support live search if it is easy. In this case, there is no "Search" button, there is a ["Done"](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5df04f8aa47344b0f512e033) button that collapses the two input fields into one.

* Initial screen: 
https://zpl.io/VkzBBWW
* With focus on key words input 
https://zpl.io/Vq5ZZLG
* With focus on location input 
https://zpl.io/2ZB99ZE
* With both fields are populated, note truncation of search strings to save screen space 
https://zpl.io/a3DkZpN

Acceptance criteria:
- [ ]  Incorrect font for both search input field - ensure it’s Avenir Book.
- [ ]  Opacity for texts within search input fields should change according to its state: 1) with placeholder text - 60%, GreyishBrown, 2) with user input - 100%, Black.
- [ ]  Search input fields are white (#ffffff) - the background, not the text.
- [ ]  Typing indicator should be in black instead of green in iOS.
- [ ]  “X” icon for both search input fields should be white instead of black.
- [ ]  “My location” button should have a right-padding of 16dp. Refer to https://zpl.io/2ZB99ZE.
- [ ]  Touch area for the “X” icon is too small, make sure it is easy to clickable.
- [ ]  Back button is removed from Search
- [ ]  'Show more service' button display the text properly (not cut off nor go to next line)
- [ ]  Both search input icons are aligned and from MaterialIcon pack

Steps to QA:
1. Go to search screen
2. The search screen should have 2 input fields that look this mock 
https://zpl.io/VkzBBWW
3. Type into search term input, the results should update live
4. Click on X to the right of the search term input and should clear the input field
5. Type in another search term
6. Click on the location input field and the My location button should appear. Refer to this mock: 
https://zpl.io/2ZB99ZE
7. Accept permissions if necessary and the results should reflect your current location
8. Click on X to the right of location input should clear the field
9. Manually type in a city like 'Surrey' and the results should update
10. Scroll to the bottom of search results and there should be a `find more services` button if the results is longer than 20 item. Refer to this mock: https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5df04f8ad731a2a4441970ed
11. Click on the more services button and more related services should load.

**Comment by ian-lin-PG** [comment]
@cherrielam @aron-chen-pg @rasmus-storjohann-PG 
This is the updated search input fields based mostly on mock#2 that is in the issue.
![image](https://user-images.githubusercontent.com/52009863/71281532-ff6df080-2312-11ea-86bc-4f62e4306499.png)

**Comment by ian-lin-PG** [comment]
Here is an update with the `My Location` button. It's here and functional.
![image](https://user-images.githubusercontent.com/52009863/71594341-6bf3a700-2aec-11ea-9eac-3de59d71ac8b.png)

**Comment by rasmus-storjohann-PG** [comment]
Merged the PR, found one issue:
*    Open search page
*    Enter some search terms and get the results
*    Click on a service to open the service detail
*    Click the back button
*    Expected: The search terms are still there
*    Observed: The search screen input fields have been reset to empty

**Comment by ArtiBPG** [comment]
@ian-lin-PG the Done button that you see in the mocks is missing on Android. Is that intentional?

**Comment by ian-lin-PG** [comment]
@ArtiBPG 
* The done button is omitted for now because live search is enabled and it's not necessary to click done to start the search. It can be included in [this issue](https://github.com/pg-irc/pathways-frontend/issues/957) such that when click done the 2 input fields merge into 1. I will consult with you and @aron-chen-pg  when I get to that issue.

* The empty state mock and the partial translation for the service listings are tracked [here](https://github.com/pg-irc/pathways-frontend/issues/939)

Let me know if splitting up the issue this way is confusing.

**Comment by ArtiBPG** [comment]
@jparlina tested for Android, test on iPhone.

**Comment by aron-chen-pg** [comment]
With the updated design, we no longer have the "Done" button. I've updated the Zeplin link within this issue to reflect the change.

**Comment by aron-chen-pg** [comment]
Tested on iPhone X, aside from UI refinement and other concerns that were already raised, search inputs are functioning as expected.

**Comment by ian-lin-PG** [comment]
- [x]  Incorrect font for both search input field - ensure it’s Avenir Book.
- [x]  Opacity for texts within search input fields should change according to its state: 1) with placeholder text - 80%, 2) placeholder text but focused - 30%, 3) with user input - 100%.
- [x]  Search input fields are white (#ffffff) with 30% opacity.
- [x]  Typing indicator should be in white instead of green.
- [x]  “X” icon for both search input fields should be white instead of black.
- [x]  “My location” button should have a right-padding of 16dp. Refer to https://zpl.io/2ZB99ZE. Please provide me both the left and right padding for the search input field and “My Location” button.
- [x]  Touch area for the “X” icon is too small. Refer to deck: https://drive.google.com/open?id=1Q70fNaakoOWnogR6Ws9_sjBkFGyqdpmW.
-  [x]  Back button is removed from Search
-  [x]  'Show more service' button display the text properly (not cut off nor go to next line)

**Comment by tomy-pg** [comment]
This issue has been separated into various other issues in the past few months. 
Related issues: 
Search input field styling and collpasing: #957 and #1030 
Show more services button: #1058 

Closing.
