### ISSUE TITLE
Search term is empty when heading back to search page from service detail

### ISSUE THREAD

**Issue by ian-lin-PG** [pg-irc/pathways-frontend#956]
Search term is empty when heading back to search page from service detail

### Acceptance Criteria 
- [x]  Search term is still there after clicking back from any service detail page.

### Nice to Have
- [ ]  Bonus if the search result is also there and doesn't trigger a brand new search
### Steps for QA: 
1. Open search page
2. Enter some search terms and get the results
3. Click on a service to open the service detail
4. Click the back button
5. The search terms are still there

**Comment by aron-chen-pg** [comment]
@ian-lin-PG Adding on to this bug, say if the input does persist, does the scrolling position persist as well?

**Comment by ian-lin-PG** [comment]
Only the input will persist. As far as I know search caching is only in browser version of algolia.

**Comment by aron-chen-pg** [comment]
The ideal experience would be to keep the search input + the scroll position on the service listing. That way when users want to continue to explore other services, they don't have to scroll again just to skip through services that have already seen. Upon reading some articles, I think one of the ways to address this issue could simply be turning our service detail (page) into a modal instead. That way all the data will be preserved since it will just be a new overlay on top of the existing page.

**Comment by tomy-pg** [comment]
Staging version 1.18.0:

- [x] Search term is still there after clicking back from any service detail page. 
- [ ] Bonus if the search result is also there and doesn't trigger a brand new search.

Closing as this meets requirement but not bonus.
